#!/bin/bash

# ----------------------- JOB PARAMETERS ---------------------- #

#BSUB -J task4

#BSUB -q hpc

#BSUB -n 24

#BSUB -R "rusage[mem=1GB]"

#BSUB -R "select[model == XeonE5_2650v4] span[hosts=1]"

#BSUB -W 16:00

#BSUB -o ./batch/task4_%J.out
#BSUB -e ./batch/task4_%J.err

# ----------------------- JOB DEFINITION --------------------- #

for i in $(seq 1 10); do
  echo "trial $i/10"
  ./.venv/bin/python3.12 -m padding_oracle.cli timing --message-kb 16
done
