#!/bin/bash

# ----------------------- JOB PARAMETERS ---------------------- #

#BSUB -J task4

#BSUB -q hpc

#BSUB -n 24

#BSUB -R "rusage[mem=1GB]"

#BSUB -R "select[model == XeonE5_2650v4] span[hosts=1]"

#BSUB -W 16:00

#BSUB -o ./batch/task4_%J.out
#BSUB -e ./batch/task4_%J.err

# ----------------------- JOB DEFINITION --------------------- #

./.venv/bin/python3.12 -m padding_oracle.cli task4 --trials 10 --jitters-ms "0,0.01,0.05,0.1,0.5,1,5" --message-kb 16
