#!/bin/bash

# ----------------------- JOB PARAMETERS ---------------------- #

#BSUB -J task4

#BSUB -q hpc

#BSUB -n 1

#BSUB -R "rusage[mem=1GB]"

# BSUB -R "select[model == XeonE5_2650v4] span[hosts=1] affinity[socket(1)]"

#BSUB -W 00:45

#BSUB -o ./batch/task4_%J.out
#BSUB -e ./batch/task4_%J.err

# ----------------------- JOB DEFINITION --------------------- #


./.venv/bin/python3.12 -m padding_oracle.cli task4
