#!/bin/bash

# ----------------------- JOB PARAMETERS ---------------------- #

#BSUB -J task3

#BSUB -q hpc

#BSUB -n 1

#BSUB -R "rusage[mem=1GB]"

# BSUB -R "select[model == XeonE5_2660v3] span[hosts=1] affinity[socket(1)]"

#BSUB -W 00:45

#BSUB -o ./batch/test_%J.out
#BSUB -e ./batch/test_%J.err

# ----------------------- JOB DEFINITION --------------------- #


./.venv/bin/python3.12 -m padding_oracle.cli task3 --mac-work 0 --initial-samples 32 --refine-samples 128 --top-k 16

./.venv/bin/python3.12 -m padding_oracle.cli task3 --mac-work 0 --initial-samples 64 --refine-samples 256 --top-k 32

